theme: jekyll-theme-dinky
title: Boston-area Data Privacy
description: A web site for a group of researchers working on data privacy at Boston University, Harvard, and Northeastern.

show_downloads: "false"
